### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by gusilveiramp** [toystars/react-native-geo-fence#2]
Hi,

I'm using RN 0.49 and Two other external libraries: react-native-maps and wix-react-native-navigation
Can help?

:react-native-geo-fence:incrementalReleaseJavaCompilationSafeguard
:react-native-geo-fence:compileReleaseJavaWithJavac
:react-native-geo-fence:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
C:\project\node_modules\react-native-geo-fence\android\src\main\java\com\bmustapha\reactlibrary\RNGeoFencePackage.java:19: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error
:react-native-geo-fence:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-geo-fence:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by gusilveiramp** [comment]
I figured out how to fix.
Just remove the @override from the file node_modules\react-native-geo-fence\android\src\main\java\com\bmustapha\reactlibrary\RNGeoFencePackage.java

**Comment by toystars** [comment]
This has been fixed
